'use strict';

(function () {
  var LOCATION_Y_MIN = 130;
  var LOCATION_Y_MAX = 630;
  var MAP_PIN_HEIGHT = 70;
  var MAP_PIN_WIDTH = 50;
  var ESC_KEYCODE = 27;

  window.utils = {
    LOCATION_Y_MIN: LOCATION_Y_MIN,
    LOCATION_Y_MAX: LOCATION_Y_MAX,
    MAP_PIN_HEIGHT: MAP_PIN_HEIGHT,
    MAP_PIN_WIDTH: MAP_PIN_WIDTH,
    ESC_KEYCODE: ESC_KEYCODE
  };
})();
